- menu_name: "Site Services"

- name: "Contact"
  url: "/contact/"
  title: "ENES contact"

#- name: "Mailinglist"
#  url: "https://lists.enes.org/mailman/listinfo/is-enes3"
#  title: "Subscribe to mailinglist"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "ENES privacy policy"

- name: "Credits"
  url: "/credits/"
  title: "Site and photo credits"
